### ISSUE TITLE
 ErrorException  : Undefined property: stdClass::$SessionId

### ISSUE THREAD

**Issue by pedmindset** [jowusu837/hubtel-ussd-plugin-laravel#2]
ErrorException  : Undefined property: stdClass::$SessionId

  at C:\Users\MERSIE\LaravelProjects\dispose\vendor\jowusu837\hubtel-ussd-plugin-laravel\src\MainController.php: 63
  59:         $this->response = new UssdResponse();
  60:
  61:         // Set request
  62:         $this->request = (object) $request->json()->all();
  63:         $this->sessionId = 'hubtel_ussd_session_' . $this->request->SessionId;
  64:
  65:         // Check if cache is set
  66:         $this->session = $this->retrieveSession();
  67:     }
  68:

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined property: stdClass::$SessionId", "C:\Users\MERSIE\LaravelProjects\dispose\vendor\jowusu837\hubtel-ussd-plugin-laravel\src\MainController.php", [Object(Illuminate\Http\Request)])
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\jowusu837\hubtel-ussd-plugin-laravel\src\MainController.php : 63

  2   Jowusu837\HubtelUssd\MainController::__construct(Object(Illuminate\Http\Request))
      [internal] : 0

  Please use the argument -v to see more details.
PS C:\Users\MERSIE\LaravelProjects\dispose> php artisan route:list -v

   ErrorException  : Undefined property: stdClass::$SessionId

  at C:\Users\MERSIE\LaravelProjects\dispose\vendor\jowusu837\hubtel-ussd-plugin-laravel\src\MainController.php: 63
  59:         $this->response = new UssdResponse();
  60:
  61:         // Set request
  62:         $this->request = (object) $request->json()->all();
  63:         $this->sessionId = 'hubtel_ussd_session_' . $this->request->SessionId;
  64:
  65:         // Check if cache is set
  66:         $this->session = $this->retrieveSession();
  67:     }
  68:

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Undefined property: stdClass::$SessionId", "C:\Users\MERSIE\LaravelProjects\dispose\vendor\jowusu837\hubtel-ussd-plugin-laravel\src\MainController.php", [Object(Illuminate\Http\Request)])
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\jowusu837\hubtel-ussd-plugin-laravel\src\MainController.php : 63

  2   Jowusu837\HubtelUssd\MainController::__construct(Object(Illuminate\Http\Request))
      [internal] : 0

  3   ReflectionClass::newInstanceArgs()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\Container.php : 800

  4   Illuminate\Container\Container::build("Jowusu837\HubtelUssd\MainController")
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\Container.php : 646

  5   Illuminate\Container\Container::resolve("Jowusu837\HubtelUssd\MainController", [])
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\Container.php : 601

  6   Illuminate\Container\Container::make("Jowusu837\HubtelUssd\MainController", [])
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Foundation\Application.php : 734

  7   Illuminate\Foundation\Application::make("Jowusu837\HubtelUssd\MainController")
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Routing\Route.php : 226

  8   Illuminate\Routing\Route::getController()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Routing\Route.php : 796

  9   Illuminate\Routing\Route::controllerMiddleware()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Routing\Route.php : 757

  10  Illuminate\Routing\Route::gatherMiddleware()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php : 151

  11  Illuminate\Foundation\Console\RouteListCommand::getMiddleware(Object(Illuminate\Routing\Route))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php : 114

  12  Illuminate\Foundation\Console\RouteListCommand::getRouteInformation(Object(Illuminate\Routing\Route))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php : 86

  13  Illuminate\Foundation\Console\RouteListCommand::Illuminate\Foundation\Console\{closure}(Object(Illuminate\Routing\Route))
      [internal] : 0

  14  array_map(Object(Closure))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Support\Collection.php : 932

  15  Illuminate\Support\Collection::map(Object(Closure))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php : 87

  16  Illuminate\Foundation\Console\RouteListCommand::getRoutes()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Foundation\Console\RouteListCommand.php : 75

  17  Illuminate\Foundation\Console\RouteListCommand::handle()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  18  call_user_func_array([])
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 29

  19  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 87

  20  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php : 31

  21  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Container\Container.php : 564

  22  Illuminate\Container\Container::call()
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Console\Command.php : 184

  23  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\symfony\console\Command\Command.php : 251

  24  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Console\Command.php : 171

  25  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\symfony\console\Application.php : 886

  26  Symfony\Component\Console\Application::doRunCommand(Object(Illuminate\Foundation\Console\RouteListCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\symfony\console\Application.php : 262

  27  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\symfony\console\Application.php : 145

  28  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Console\Application.php : 89

  29  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\Users\MERSIE\LaravelProjects\dispose\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php : 122

  30  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      C:\Users\MERSIE\LaravelProjects\dispose\artisan : 37

**Comment by pedmindset** [comment]
I was using the method to access the route... its working fine now..

**Comment by nanadjei** [comment]
@pedmindset Can you show me an example because am also getting the same error.

**Comment by pedmindset** [comment]
How did u get the error

**Comment by nanadjei** [comment]
I copied his mainController and wanted to use it but am getting  `ErrorException : Undefined property: stdClass::$SessionId`

**Comment by pedmindset** [comment]
Okay.. the MainController is accessed through a post route where hubtel will send the SessionId. If you try to access it manually you get that error... 

If you check the code u will find it.. I guess the code was not written with mocking and testing in mind... But you can fork it and make some changes....

**Comment by pedmindset** [comment]
You can also send the required params to the ussd route as a post request, you should get a response in your broswer..

Check hubtel docs for request and response fields..

**Comment by nanadjei** [comment]
So in your controller are you doing something similar to what he did in his mainController or you are doing

    class HomeActivity extends UssdActivity 
       {
            public function run() {
             $this->response->Type = UssdResponse::RELEASE;
             $this->response->Message = 'Ussd is working!';
            return $this;
         }

       public function next() {
          return MenuSelection::class;
        }
      }

**Comment by pedmindset** [comment]
Yea

**Comment by nanadjei** [comment]
In the Initiation stage, I have an index method calling my 1st activity that is the HomeActivity class but I called it WelcomeActivity but it looks like it is not getting the response. This is the controller method

       public function index(Request $request)
          {
              // $ussdRequest = json_decode(file_get_contents('php://input'));
              $ussdRequest = (object)$request->json()->all();

              $response = new UssdResponse();

              $sessionId = $ussdRequest->SessionId;

              return (new WelcomeActivity($ussdRequest, $response, $sessionId)); 
          }

**Comment by pedmindset** [comment]
Dont change the implementation on MainContoller..

MainContoller sets up the request and response btw your activity and hubtel... 
what you can do is extend UssdActivity Class by adding extra methods and also using php traits on your Activity classes

because your activity classes (WelcomeActivity has access to the lib classes (UssdActivity, UssdResponse, UssdRequest and sessions) so you can use them as you wish...

**Comment by pedmindset** [comment]
why dont you tell me what you want to achieve

**Comment by nanadjei** [comment]
Thanks Emma. I copied MainController code into my controller and that
solved the problem.
